### ISSUE TITLE
Missing dependencies in packaged Electron app

### ISSUE THREAD

**Issue by jdpigeon** [alexcastillo/eeg-pipes#20]
There's an error that is popping up in the release builds of my Electron app using the library: `Error: Cannot find module 'babel-runtime/helpers/extends'`

I think this is related to the babel and webpack mess you got embroiled in when we introduced the createEEG operator, @alexcastillo, but I can't remember exactly where we left it. Wasn't there a fix for the issue we encountered? Maybe it hasn't been published to the npm versions of webpack yet?

**Comment by alexcastillo** [comment]
Let me check.

**Comment by jdpigeon** [comment]
Should we just add babel-runtime as a dependency?

**Comment by alexcastillo** [comment]
It should be a dev dependency.

**Comment by jdpigeon** [comment]
Rolling back to eeg-pipes 1.1.0 before the webpack 4 upgrade fixes the issue

**Comment by jdpigeon** [comment]
Solved this issue by removing webpack externals when building for Electron https://github.com/alexcastillo/eeg-pipes/pull/21 and moving eeg pipes to the `app/package.json` in electron-react-boilerplate's [two package.json structure](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure)
