### ISSUE TITLE
Changing filter operators on the fly

### ISSUE THREAD

**Issue by jdpigeon** [alexcastillo/eeg-pipes#3]
So, I've spent a quite a bit of time trying to find a way to change the type of filter applied to a stream of EEG data while it's being collected. Hopefully, we get to the point where we can swap operators in and out of an eeg pipe based on business logic.

Here I have an EEG epic (redux-observable) that uses `switchMap` to change the filter operator that is applied to an EEG stream based on emitted actions. The insight I had that let me do this was place the actual EEG data observable inside an observable listening for filter info actions (also inside another observable listening for graph start actions). As far as I can tell, the filter is getting applied immediately and I'm not losing any data. However, either the inner eeg data observable doesn't unsubscribe or the filter functions stack on top of each other because after switching filters once the graph gets all messed up. As if two listeners are writing to the same graph.

```js
const setupGraphUpdate = (action$, store) =>
  action$.ofType(START_GRAPHING).pipe(
    filter(() => store.getState().device.eegObservable != null),
    switchMap(() =>  // SwitchMap to only propagate events from most recent filter type observaable
      action$.ofType(SET_FILTER_INFO).pipe(
        tap(() => console.log("filter changed")),
        pluck("payload"), //Extracts filterInfo
        switchMap(filterInfo =>
          store.getState().device.eegObservable // Upstream observable stored in Redux
          .pipe(
            groupByChannel(),
            defineFilter(filterInfo), // Switch function returns appropriate filter operator
            map(updateEEGBuffer),
            takeUntil(action$.ofType(RESET_FILTER))
          )
        )
      )
    ),
    catchError(error =>
      Observable.of(error).pipe(
        tap(p => console.log("setupGraphUpdate", p)),
        map(viewerError)
      )
    ),
    takeUntil(action$.ofType(STOP_GRAPHING, VIEWER_CLEANUP))
  );
```

Any idea what might be going wrong here and what the best solution will be going forward?

**Comment by alexcastillo** [comment]
Try replacing `takeUntil` with `take(1)`.

**Comment by jdpigeon** [comment]
The current implementation I'm using isn't as elegant as what I was trying to do above, but it appears to be  working just fine.

Instead of using Redux Observable Middleware, all I do is keep a reference to an `eegObservable` and a `filterObservable` in the store. Components that need to use filtered data just subscribe to `filterObservable` as they need to. When I want to change filters, I just dispatch an action that cancels the previous `filterObservable` and replaces it with a new one. Then, each component's `componentWillReceiveProps` function resubscribes when they detect a new `filteredObservable` prop.

When I change filters this way the data keeps streaming continuously and I can hardly notice any disruption
